# Test the entire process of RGBPP to ensure the proper functioning of the rgbpp-sdk package.

name: Integration Tests

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env_set: [ xudt, spore ]

    steps:
      - name: Checkout rgbpp-sdk
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v3
        name: Install -g pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm run build:packages

      - name: Set environment variables
        run: |
          echo "VITE_SERVICE_URL=${{ secrets.SERVICE_URL }}" >> $GITHUB_ENV
          echo "VITE_SERVICE_TOKEN=${{ secrets.SERVICE_TOKEN }}" >> $GITHUB_ENV
          echo "VITE_SERVICE_ORIGIN=${{ secrets.SERVICE_ORIGIN }}" >> $GITHUB_ENV
          echo "INTEGRATION_CKB_PRIVATE_KEY=$(if [ '${{ matrix.env_set }}' == 'xudt' ]; then echo ${{ secrets.INTEGRATION_CKB_PRIVATE_KEY }}; else echo ${{ secrets.INTEGRATION_CKB_SPORE_PRIVATE_KEY }}; fi)" >> $GITHUB_ENV
          echo "INTEGRATION_BTC_PRIVATE_KEY=$(if [ '${{ matrix.env_set }}' == 'xudt' ]; then echo ${{ secrets.INTEGRATION_BTC_PRIVATE_KEY }}; else echo ${{ secrets.INTEGRATION_BTC_SPORE_PRIVATE_KEY }}; fi)" >> $GITHUB_ENV
            
      - name: Run integration:xudt/spore script
        working-directory: ./tests/rgbpp
        run: |
          if [ "${{ matrix.env_set }}" = "xudt" ]; then
            pnpm run integration:xudt
          elif [ "${{ matrix.env_set }}" = "spore" ]; then
            pnpm run integration:spore
          fi
